name: Update README

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        uses: peaceiris/actions-readme@v2
        with:
          toc: true
          exclude: 'LICENSE|README.md|.github'
          exclude-pattern: '.png|.gif|.jpg|.jpeg|.ipynb|.pdf|.zip'
          enable-pages: true
          enable-auto-prune: true
          enable-wordwrap: true
          script: |
            # Collect folder list and last updated date
            FOLDERS=$(find . -type d -not -path './.git/*' -not -path '.' | sed 's|^./||')
            for FOLDER in $FOLDERS; do
              DATE=$(git log -1 --format="%cd" --date=short -- $FOLDER)
              echo "- [$FOLDER](https://github.com/${{ github.repository }}/tree/main/$FOLDER), Last Updated: $DATE" >> temp.txt
            done
            
            # Append to README.md
            sed '/<!-- FOLDER LIST -->/q' README.md > temp.md
            cat temp.txt >> temp.md
            echo "<!-- FOLDER LIST -->" >> temp.md
            sed -n -e '/<!-- UPDATE START -->/,$p' README.md >> temp.md
            mv temp.md README.md
